"""
Embed Worker - embedding-based signal classification.
Runs independently from LLMWorker. Does NOT use LLM.

Called by cron (every minute) via skill command 'run_embed_worker'.

Responsibilities:
  - Fetch raw signals that have no processed_signals row
  - Classify them via cosine similarity against rule embeddings (EmbedProcessor)
  - Save results with summary=null (summary is generated by LLMWorker.summarize_batch)

Worker guarantees:
  - File lock inside EmbedProcessor prevents concurrent runs
  - Fast: single cron tick processes up to batch_size * max_batches_per_run signals
  - No LLM calls, no network calls except to local embedder HTTP service
"""

from __future__ import annotations

import logging
from typing import Any

from storage.postgres import PostgresStorage

log = logging.getLogger(__name__)


class EmbedWorker:
    """
    Embedding-based classification worker.
    Instantiated and called once per cron tick via cmd_run_embed_worker.
    """

    def __init__(self, config: dict[str, Any], storage: PostgresStorage) -> None:
        self._config = config
        self._storage = storage

    def run(self) -> dict[str, Any]:
        """
        Run embedding classification for pending raw signals.
        Returns summary dict with classified count and remaining unprocessed count.
        """
        from core.llm_router import LLMRouter  # noqa: PLC0415
        from core.orchestrator import Orchestrator  # noqa: PLC0415

        unprocessed = self._storage.count_unprocessed()
        if unprocessed == 0:
            log.info("[embed_worker] no unprocessed signals, idle")
            return {"status": "idle", "note": "No unprocessed signals."}

        max_batches = self._config.get("processor", {}).get("max_batches_per_run", 5)

        # LLMRouter is required by Orchestrator.process signature but EmbedProcessor
        # does not use it for classification - only kept for interface compatibility
        router = LLMRouter(self._config)
        orch = Orchestrator(self._config, self._storage)
        result = orch.process(router, max_batches=max_batches)

        log.info("[embed_worker] done: %s", result)
        return {"status": "done", **result}
